Resources:
  UsersTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'melirate-users'
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
        - AttributeName: 'timestamp'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
        - AttributeName: 'timestamp'
          KeyType: 'RANGE'
      BillingMode: 'PAY_PER_REQUEST'
